name: pinboard
version: '0.10.2.0'
synopsis: Access to the Pinboard API
description: ! '

  The Pinboard API is a way to interact programatically with

  your bookmarks, notes and other Pinboard data. This

  library wraps the API exposing functions and data

  structures suitable for usage in Haskell programs.

'
category: Network APIs
author: Jon Schoning
maintainer: jonschoning@gmail.com
copyright: Copyright (c) 2015 Jon Schoning
license: MIT
homepage: https://github.com/jonschoning/pinboard
git: git://github.com/jonschoning/pinboard.git
bug-reports: https://github.com/jonschoning/pinboard/issues
extra-source-files:
- README.md
- changelog.md
ghc-options: -Wall
dependencies:
- base >=4.6 && <5.0
- transformers >=0.4.0.0
- mtl >=2.2.1
- unliftio
- unliftio-core
- unordered-containers
library:
  source-dirs: src
  ghc-options:
  - -fwarn-incomplete-patterns
  - -funbox-strict-fields
  - -fexpose-all-unfoldings
  exposed-modules:
  - Pinboard
  - Pinboard.Api
  - Pinboard.ApiRequest
  - Pinboard.ApiTypes
  - Pinboard.ApiTypesLens
  - Pinboard.Client
  - Pinboard.Error
  - Pinboard.Types
  - Pinboard.Util
  - Pinboard.Logging
  dependencies:
  - aeson >=0.11.1 && <2.0
  - bytestring >=0.10.0 && <0.11
  - containers >=0.5.0.0 && <0.7
  - http-types >=0.8 && <0.13
  - http-client >=0.5 && <0.7
  - http-client-tls >=0.3.0 && <0.4
  - text >=0.11 && <1.3
  - time >1.3
  - vector >=0.10.9 && <0.13
  - network >=2.6.2 && <4
  - profunctors >=5
  - random >=1.1
  - monad-logger >=0.3 && <0.4
tests:
  tests:
    main: Test.hs
    source-dirs: tests
    ghc-options:
    - -fno-warn-orphans
    dependencies:
    - pinboard
    - bytestring
    - containers
    - hspec >=1.8
    - text
    - time
    - aeson
    - semigroups
    - QuickCheck
