name: gen
version: '0.1.0.0'
author: Jon Schoning
maintainer: jonschoning@gmail.com
license: MIT
source-dirs:
- ./.
- ../src
other-extensions:
- TemplateHaskell
ghc-options:
- -ddump-splices
- -rtsopts
dependencies:

- base >=4.6 && <5.0
- bytestring >=0.10.0 && <0.11
- either
- transformers >=0.4.0.0
- mtl >=2.2.1
- safe-exceptions <0.2
- unordered-containers
- lens >=4.13
- template-haskell >=2.10

- aeson >=0.11.1 && <2.0
- containers >=0.5.0.0 && <0.7
- http-types >=0.8 && <0.13
- http-client >=0.5 && <0.6
- http-client-tls >=0.3.0 && <0.4
- text >=0.11 && <1.3
- time >=1.5 && <1.9
- vector >=0.10.9 && <0.13
- network >=2.6.2 && <2.9
- profunctors >=5
- random >=1.1
- monad-logger >=0.3 && <0.4
- unliftio
- unliftio-core
executables:
  gen:
    main: Main.hs
